apiVersion: v1
kind: Service 
metadata: 
    name: tomcatapp-ci
    labels:
      app: tomcatapp-ci
spec:
    selector:
        app: tomcatapp
    ports:
        - protocol: TCP
          port: 8080 
          targetPort: 8080 
    type: ClusterIP