apiVersion: apps/v1 
kind: DaemonSet
metadata:
    name: cwagent   
    labels:
       app: cwagent
spec:
    selector: 
        matchLabels:
           app: cwagent 
    template:
        metadata: 
          name: cwagent   
          labels:
            app: cwagent 
        spec:
           containers:
              - name: nginx 
                image: nginx
                ports:
                - containerPort: 80