apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-pod
spec:
  containers:
  - name: new-container
    image: nginx:latest
    resources: 
        requests:    #starting point of our pod's resouce
             cpu: "25m"
             memory: "50Mi"
        limits:      #endpoint point of ours pod's resource
            cpu: "50m"
            memory: "100Mi"  
    ports:
    - containerPort: 80
--- 
apiVersion: v1
kind: Service 
metadata:
  name: my-service
spec:
  selector:   
    app: my-pod
  ports:
  - protocol: TCP
    port: 80  #container port
    targetPort: 80 #port on the pod
  type: LoadBalancer  #NodePort service type #ClusterIP is default 
