apiVersion: v1
kind: ReplicationController
metadata:   
      name: replicacontroller
      labels:
        app: replicacontrollerapp
spec: 
    selector: 
        app: replicacontrollerapp
    replicas: 3
    template:
        metadata: 
          labels:
              name: new-app
              app: replicacontrollerapp
        spec:
            containers: 
                - name: nginx 
                  image: nginx:latest
                  resources: 
                    requests:
                      cpu: "500m"
                      memory: "128Mi" 
                  ports: 
                      - containerPort: 80
                        name: http
                        protocol: TCP