# apiVersion:  apps/v1  
# kind:   StatefulSet
# metadata: 
#       name: statefulset
#       labels:
#           app: statefullapp
#       spec:
#           replicas: 4
#           selector:
#             matachlabels:
#               app: statefullapp
#           template:
#             metadata: 
#               labels:
#                   name: new-statefullapp
#                   app:  statefullapp #replicasetapp1 change when using NotIn exp
#             spec:
#                 containers: 
#                     - name: mysql 
#                       image: mysql:latest
#                       resources: 
#                         requests:
#                           cpu: "100m"
#                           memory: "128Mi" 
#                       ports: 
#                           - containerPort: 3306
#                             name: http
#                             protocol: TCP
#                       env:
#                           - name: MYSQL_ROOT_PASSWORD
#                             value: "1234"

apiVersion: apps/v1
kind:  StatefulSet
metadata: 
  name: statefull
  labels:
    app: depapp
spec:
    selector: 
      matchLabels: 
          app: depapp
    replicas: 4
    template:
      metadata:
        labels:
          name: mdb
          app: depapp
      spec:
        containers:
          - name: mysql
            image: mysql
            resources: 
                requests:
                  cpu: "100m"
                  memory: "128Mi
            ports:
                - containerPort: 3306
                  protocol: TCP
            env:
              - name: MYSQL_ROOT_PASSWORD
                value: "1234"      



#111111
#12122121

#12121212
#sdsdewe
#121212
#24344545465654757
