apiVersion: v1
kind: Service 
metadata: 
    name: nginxappci
    labels:
      app: nginxappci 
spec:
    selector:
        app: nginxapp
    ports:
        - protocol: TCP
          port: 80 
          targetPort: 80 
    type: ClusterIP