apiVersion: v1
kind: PresistentVolume 
metadata:
  name: pv-volume 
  labels: 
    type: pv 
spec:
   storageClassName: standard 
   volumeMode: Filesystem
   capacity: 
      storage: 15Gi 
   accessModes:
       - ReadWriteOnec 
   persistentVolumeReclaimPolicy: Retain 
   hostPath:
      path: "/mnt/data"