apiVersion: v1 
kind: presistentVolumeClaim
metadata:
   name: pv-claim 
spec: 
   storageClassName: standard
   volumeMode: Filesystem
   accessModes:
      - ReadWriteOnce
   resources:
      requests:
         storage: 12Gi