
apiVersion: v1
kind: Service
metadata: 
  name: nginxsrv
spec:
  type: ClusterIP
  selector:
    app: deployappnginx 
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP