apiVersion: v1
kind: Pod
metadata: 
  name: nginxci
  labels:
    app: nginxci
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80

---    
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  type: ClusterIP 
  selector: 
      app: nginxci
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80