apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: my-ns
  labels:   
    app: myapp 
spec:
  containers:
  - name: my-container
    image: nginx:1.14.2
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myserviceclusterip
  namespace: my-ns
  
spec:
  selector:
    app: myapp
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: v1  
kind: Namespace
metadata:
  name: my-ns 
  labels:   
    app: myapp
