apiVersion: apps/v1  
kind: DaemonSet
metadata:
  name: daemonset 
  labels: 
      app: daemonset
spec:
  selector: 
    matchLabels:
      app: daemonset 
  template:
    metadata: 
     name: cwagent-pod 
     labels: 
          app: daemonset
    spec: 
        containers:
          - name: cwagent-container 
            image: amazon/cloudwatch-agent
            ports:
              - containerPort: 80

          


