apiVersion: v1 
metadata: 
     name: pod-ci 
     app: podci  #tags  
kind:  Pod
spec: 
     containers:
      - name: nginx-container 
        image: nginx-latest 
        ports:
          - containerPort: 80

--- 
apiVersion: v1
metadata: 
    name: ci-service
kind: Service
spec: 
    selector:
        app: podci
    ports:
      - protocol: TCP 
        port: 80 
        targetPort: 80