apiVersion: v1 
metadata: 
      name: pod-ci 
      labels:
        app: podci  #tags  
kind:  Pod
spec: 
     containers:
      - name: nginx-container 
        image: nginx
        ports:
          - containerPort: 80

--- 
apiVersion: v1
metadata: 
    name: ci-service
kind: Service
spec: 
    selector:
        app: podci
    type: ClusterIP
    ports:
      - protocol: TCP 
        port: 80 
        targetPort: 80
        

 #kubectl expose pod cipod  --port=80 --target-port=80 --type=ClusterIP