apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dbapp 
  labels:
    app: dbapp 
spec: 
  replicas: 3
  template:
    metadata:
      labels:
        app: dbapp 
    spec: 
      containers:
      - name: dbapp 
        image: mysql 
        ports:
            -  containerPort: 3306
               protocol: TCP
        env: 
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets
                key: dbrootpw
  selector:
    matchLabels:
      app: dbapp          