
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployappnginx
  labels:
      app: deployappnginx
spec:
    replicas: 2     #desiredstate
    strategy: 
          type: RollingUpdate
    selector: 
          matchLabels:
            app: deployappnginx
    template: 
        metadata: 
            labels: 
              app: deployappnginx   
        spec: 
          containers:
             - name: deployappnginx
               image: nginx:latest
               ports:
                  - containerPort: 80
                    protocol: TCP
               resources:
                  requests:
                        memory: "64Mi"
                        cpu: "125m"
                  limits:     
                        memory: "128Mi"
                        cpu: "250m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployappnginx
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20