apiVersion: v1 
kind: PeristentVolume
metadata:
     name: pv-volume
     labels:
       app: pv-volume
spec:
    storageClassName: standard  #wil change based on the external storage.
    volumeMode: Filesystem #since block storage is used we use filesystem vmode
    accessModes:
      - ReadWriteOnce   #data or storage or the external drive can be mounted on 1 node and all the pods in that node cam access the storage
    capacity: 
       storage: 20Gi #maximum capacity this pv can transfer data
    hostPath:
       path: "/mnt/data/nginxvol1"
    persistentVolumeReclaimPolicy: Retain  #how data will kept either intact or recyle by pv once storage is transfer to drive.