apiVersion: v1  #official library to create pod
kind: Pod   #unique naming convention to create 
metadata: 
   name: nginxcipod
   labels:   #tags
        app: nginxcipod
spec:
    containers:
        - name: nginxcipod
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
   name: clusteripsvc
spec:
   type: ClusterIP
   selector:
        app: nginxcipod
   ports: 
      - protocol: TCP 
        port: 80 #pod port 
        targetPort: 80 # container 

