apiVersion: v1  #official library to create pod
kind: Pod   #unique naming convention to create 
metadata: 
   name: nginxpod
   labels:   #tags
        app: webapppod
spec:
    containers:
        - name: nginxpod
          image: nginx:latest
          ports:
            - containerPort: 80