apiVersion: apps/v1
kind:   Deployment
metadata: 
      name:  deploymentapp 
      labels: 
            app: deploymentapp
spec:
    replicas: 1   #desired state 
    strategy: 
        type: RollingUpdate
    template:
          metadata: 
                name: deploymentapp 
                labels:
                      app: deploymentapp
          spec:
              containers:
                  - name: http
                    image: ubuntu:latest
                    resources: 
                        requests:
                            cpu: "50m"   #1000millicore = 1 core ,  starting resource point for pod 
                            memory: "50Mi"
                        limits:
                            cpu: "100m"    #ending resource point for pod
                            memory: "100Mi"
                    ports:
                         - name: http
                           containerPort: 80
                           protocol: TCP                            
    selector:
          matchLabels:
                app: deploymentapp
--- 
apiVersion:  autoscaling/v2
kind:  HorizontalPodAutoscaler
metadata:  
    name: hpa1 
    labels:
        app: hpa1
spec:       
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: deploymentapp
    minReplicas: 1 
    maxReplicas: 2 
    metrics:
        - type: Resource
          resource:
              name: cpu
              target:
                  type: Utilization
                  averageUtilization: 10   #10% of 100m = 50m  60m traffic hpa will scale up.