apiVersion:  v1 
kind: Service
metadata:
   name: npci
   labels:
     app: npci
spec:
    selector:
         app: nginx 
    ports:
       - protocol: TCP
         port: 80
         targetPort: 80
    type: ClusterIP
    
