services: 
        studentapp:
           build: .
           ports: "8080:8080"
           container_name: studentapp_container
           #volumes:
             #- ./src:/opt/apache-tomcat-9.0.106/webapps
           #network_mode: host 
           #push: true
           tags:
             - anupdudhe/studentapp:latest