FROM ubuntu:20.04
LABEL maintainer="dev anup"
RUN apt update && \
    apt install unzip  openjdk-11-jdk -y     
 
ADD   https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.107/bin/apache-tomcat-9.0.107.zip /opt 
WORKDIR /opt
RUN   unzip apache-tomcat-9.0.107.zip
COPY context.xml /opt/apache-tomcat-9.0.107/conf/context.xml 
ADD https://s3-us-west-2.amazonaws.com/studentapi-cit/student.war /opt/apache-tomcat-9.0.107/webapps/student.war
ADD https://s3-us-west-2.amazonaws.com/studentapi-cit/mysql-connector.jar /opt/apache-tomcat-9.0.107/lib/mysql-connector.jar

RUN chmod +rwx /opt/apache-tomcat-9.0.107/bin/*.sh
EXPOSE 8080
CMD ["/opt/apache-tomcat-9.0.107/bin/catalina.sh", "run"]