services:
  tomcatwebsever:
        build: .
        ports:
            - "8080:8080"
        container_name: tomcatwebsever 
        #volumes:
            #- ./html:/opt/apache-tomcat-9.0.106/webapps
        #network_mode: "host" 
        #restart: always 
  tomcatwebseveremp:
        build: /mnt/
        ports:
            - "81:8080"
        container_name: tomcatwebseveremp