apiVersion:  v1 
kind: Pod
metadata: 
  name: nginxci-pod 
  labels:
    app: nginxci
spec: 
    containers:
       - image: nginx:latest 
         ports:
           - containerPort: 80
         name: nginxcont 
        
---
apiVersion:  v1 
kind: Service
metadata:
  name: clusteripsvc 
spec: 
    selector: 
       app: nginxci
    type: ClusterIP 
    ports: 
         - protocol: TCP
           port: 80 #pod port
           targetPort: 80  #container port  
        
