apiVersion:  apps/v1 
kind:  DaemonSet
metadata:
   name: daemonset
   labels:
      app: ds 
spec:
   template:
      metadata: 
        name: cw-pod
        labels:
          app: cw-pod
      spec: 
          containers:
             - image: amazon/cloudwatch-agent
               ports:
                 - containerPort: 80
               name: cwcont
   selector:
       matchLabels:
            app: cw-pod
            
