apiVersion: apps/v1                            
kind: Deployment
metadata:
    name: mydeployment
    labels:
       app: my-app
spec:
  replicas: 3 
  template: 
      metadata: 
          name: app1 
          labels:
              app: app1 
      spec:
         containers:
            - name:  appcont1 
              image: nginx:latest  #v1 
              ports:
                - containerPort: 80
  selector:
    matchLabels:
       app: app1 
  stratergy: 
       type: RollingUpdate #type of stragery
       maxSurge: 1 #nos of newly updates pods created at time 
       maxUnavailable: 1 #nos of old pods deleted at time