apiVersion:  v1 
kind: Pod
metadata: 
  name: nginxlb-pod 
  labels:
    app: nginxlb
spec: 
    containers:
       - image: nginx:latest 
         ports:
           - containerPort: 80
         name: nginxcont 
        
---
apiVersion:  v1 
kind: Service
metadata:
  name: lbsvc
spec: 
    selector: 
       app: nginxlb
    type: LoadBalancer
    ports: 
         - protocol: TCP
           port: 80 #pod port
           targetPort: 80  #container port  
        
