apiVersion: v1
kind:  ReplicationController
metadata:  
    name: rc 
    labels: 
      app: rc 
spec:
  replicas: 3  #desired
  template: 
    metadata: 
      name: nginx-pod
      labels:
         app: rcapp 
    spec: 
        containers:
          - image: nginx:latest 
            ports:
              - containerPort: 80
            name: nginxcont
  selector:
    app: rcapp 