apiVersion: v1
kind: Service
metadata: 
  name: tomcatsrv
spec:
  type: ClusterIP
  selector:
    app: deployapptomcat 
  ports:
    - port: 8080
      targetPort: 8080
      name: tomcat
      protocol: TCP