apiVersion:  v1  
kind: Pod  
metadata: 
  name: nginxlb
  labels: 
   app: nginxlb
spec: 
  containers:
  - name: nginx 
    image: nginx:latest
    ports:
    - containerPort: 80
---
apiVersion:  v1 
kind: Service
metadata:
   name: loadbalancer
   labels:
     app: loadbalancer
spec:
    selector:
         app: nginxlb
    ports:
       - protocol: TCP
         port: 80
         targetPort: 80
    type: LoadBalancer
    

