apiVersion:  apps/v1 
kind: ReplicaSet
metadata: 
   name: rs-exist
   labels:
      app: rs-exist 
spec:
  selector:
    matchExpressions:
        -  { key: app, operator: Exists}
  replicas: 3
  template:
      metadata: 
        name: nginx  
        labels: 
          app: nginx-exist
      spec: 
        containers:
        - name: nginx 
          image: nginx:latest
          ports:
          - containerPort: 80