apiVersion:  apps/v1 
kind: ReplicaSet
metadata: 
   name: rs-notin
   labels:
      app: rs-notin
spec:
  selector:
    matchLabels: 
        app: nginx-ml
  replicas: 3
  template:
      metadata: 
        name: nginx  
        labels: 
          app: nginx-ml
      spec: 
        containers:
        - name: nginx 
          image: nginx:latest
          ports:
          - containerPort: 80